### ISSUE TITLE
Lord of Verminion Master Tournament

### ISSUE THREAD

**Issue by NecromancerLord** [MidoriKami/DailyDuty#138] opened 2023-04-19 02:51 UTC
The plugin interface disappears after signing up for the Lord of Verminion tournament at the gold saucer, queueing for Master Tournament, then leaving the tournament match early for a loss.  There may be other similar glitches involving Lord of Verminion, but this is the one I have experienced multiple weeks in a row.

Often, you can get the interface to come back by disabling the plugin and re-enabling it, but after this most recent update, doing so caused me to have a Dalamud error requiring an FFXIV restart.  I am unsure if that is repeatable though, since I have only experienced that once.

**Comment by MidoriKami** [comment] 2023-04-19 11:37
Can you attach a video of this happening?

**Comment by NecromancerLord** [comment] 2023-04-20 00:08
As a side-note.  I had to do the first 2 Verminion challenges on my alt to enable the tournament, which I did not record, but the interface disappeared after them as well.  The reason the video ends when I disabled the addon is because the game crashed.

This is the first time I ever recorded video on my PC.  The file was too large, so I put it on YouTube for you to view (which was also a first for me).  As of the time I'm making this comment, youtube estimates a little over 30 minutes for hd to become available, but I was able to play it in standard definition without issues.

https://youtu.be/NzqpoG22bBk

**Comment by MidoriKami** [comment] 2023-04-20 10:24
That video was extremely helpful, can you attach a copy of the dalamud.log file the next time this happens?

**Comment by NecromancerLord** [comment] 2023-04-21 00:08
Since it is easily repeatable, I forced it to happen again when I logged in.  When I was searching for the location of the dalamud.log file online, I found a page saying sometimes the output.log file is helpful too, so I included that also.
[dalamud.log](https://github.com/MidoriKami/DailyDuty/files/11291197/dalamud.log)
[output.log](https://github.com/MidoriKami/DailyDuty/files/11291198/output.log)

**Comment by MidoriKami** [comment] 2023-04-25 00:39
Just a heads up this issue isn't forgotten, I'm just not actively playing FFXIV right now, so am unable to dig into the issue at this time.

**Comment by MidoriKami** [comment] 2023-04-25 21:46
#141 Is a duplicate of this issue, however, knowing that this same problem happens with the Aesthetician makes it pretty clear what's happening.

**Comment by MidoriKami** [comment] 2023-04-26 01:58
Fixed in b31aa39970069119a22890b2291bc7d4e18fc301

**Closed by MidoriKami** 2023-04-26 01:58 UTC
